### ISSUE TITLE
Ubuntu 16.04 not show tray icon

### ISSUE THREAD

**Issue by Prototype-X** [atareao/Touchpad-Indicator#15] opened 2018-04-18 09:56 UTC
Hi, atareo
touchpad-indicator  2.1.1-0extras18.04.0

**Comment by goncharovdk** [comment] 2018-04-25 20:06
Looks like the same issue in 14.04 LTS also. No way to open Preferences GUI due to this. But it works on background and reacts to the hotkey.

**Comment by atareao** [comment] 2018-05-05 06:09
Please, execute touchpad indicator from terminal.
Thanks.

**Comment by goncharovdk** [comment] 2018-05-06 13:48
Hello Lorenzo, I tried to run it from terminal immediately when confronted this issue, but it just said something like "Another copy is already loaded" (sorry, cannot check for exact message right now).

**Comment by MartinX3** [comment] 2018-05-11 09:50
Same issue in Ubuntu 17.04, 17.10 and 18.04.

**Comment by atareao** [comment] 2018-05-12 07:31
Run touchpadindicator -s

**Comment by MartinX3** [comment] 2018-05-12 08:39
@atareao 

I did it and it gave me

```
<gettext.GNUTranslations object at 0x7f69aeb59da0>
Another instance of Touchpad-Indicator is working
```

There is no other instance.
I checked it with htop.

**Comment by atareao** [comment] 2018-05-12 11:03
You must run `touchpad-indicator -s`

**Comment by atareao** [comment] 2018-05-12 11:04
What is your desktop environment? GNOME, MATE. Plasma ?

**Comment by MartinX3** [comment] 2018-05-12 11:52
My environment is MATE

**Comment by atareao** [comment] 2018-05-13 20:06
@MartinX3 please killall touchpad-indicator and start from terminal. Copy and paste here the output

**Comment by atareao** [comment] 2018-05-15 13:03
@MartinX3 killall python3... Warning becouse you kill all python3 processes

**Comment by MartinX3** [comment] 2018-05-15 19:29
```bash
martin@Deus-Ex-Machina ~ $ killall touchpad-indicator
touchpad-indicator: Kein Prozess gefunden
martin@Deus-Ex-Machina ~ $ killall python3
python3: Kein Prozess gefunden
martin@Deus-Ex-Machina ~ $ touchpad-indicator -s
<gettext.GNUTranslations object at 0x7f8dc0643f28>
Another instance of Touchpad-Indicator is working
```
Kein Prozess gefunden = No process found

**Comment by MarioVilas** [comment] 2018-05-22 09:32
Same here. Using Ubuntu 17.10 with Gnome.

**Comment by MarioVilas** [comment] 2018-05-22 09:35
`
$ apt install touchpad-indicator
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  touchpad-indicator
0 upgraded, 1 newly installed, 0 to remove and 8 not upgraded.
Need to get 397 kB of archives.
After this operation, 1,482 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/atareao/atareao/ubuntu artful/main amd64 touchpad-indicator all 2.1.2-0extras18.04.0 [397 kB]
Fetched 397 kB in 0s (961 kB/s)            
Selecting previously unselected package touchpad-indicator.
(Reading database ... 395475 files and directories currently installed.)
Preparing to unpack .../touchpad-indicator_2.1.2-0extras18.04.0_all.deb ...
Unpacking touchpad-indicator (2.1.2-0extras18.04.0) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3) ...
Processing triggers for libglib2.0-0:i386 (2.54.1-1ubuntu1) ...
Processing triggers for libglib2.0-0:amd64 (2.54.1-1ubuntu1) ...
Setting up touchpad-indicator (2.1.2-0extras18.04.0) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu5) ...
Processing triggers for hicolor-icon-theme (0.17-1) ...
$ touchpad-indicator -s
<gettext.GNUTranslations object at 0x7f89fce5c390>
Another instance of Touchpad-Indicator is working
$ ps -Af | grep python
mario     2141  1766  0 11:28 tty2     00:00:00 /usr/bin/python3 /usr/bin/blueman-applet
mario     3928  2700  0 11:34 pts/0    00:00:00 grep --color=auto python
 mario  ~  ps -Af | grep touchpad
mario     3935  2700  0 11:34 pts/0    00:00:00 grep --color=auto touchpad
`

**Comment by MarioVilas** [comment] 2018-05-22 09:40
https://github.com/atareao/Touchpad-Indicator/blob/b668bac127d0ab335cc9d7ccddfac46f8aad58e7/src/touchpadindicator.py#L677

I'm not sure the "or len(sys.argv) > 1" is ok...

**Comment by atareao** [comment] 2018-05-22 09:55
Please @MarioVilas run `killall python3` and run again `touchpad-indicator`

**Comment by MarioVilas** [comment] 2018-05-22 10:01
Ok, I got a solution using this extension: https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by MartinX3** [comment] 2018-05-22 22:47
@MartinX3

@atareao
Are you kidding me?

**Comment by MarioVilas** [comment] 2018-05-23 07:30
@MartinX3 yeah, the -s switch does not work at all. There is a logic error in the code. The second problem is Gnome 3 is not supported, so you need to install an extension to add legacy support for the icons (or just launch the .py file with the settings dialog manually).

**Comment by MarioVilas** [comment] 2018-05-23 07:33
To be honest after this problem I found another one (the "disable the touchpad while typing" feature is sort of broken too), and looking at the code I found all sort of problems (bad coding style, print debugging all over the place, exceptions being ignored, exceptions being printed instead of using the traceback module...) that I just gave up. :/

**Comment by atareao** [comment] 2018-05-23 12:30
@MarioVilas why?

**Comment by MartinX3** [comment] 2018-06-03 11:26
@atareao 
Why is this issue still closed?
I want a tray icon or I can't use this software.
I use Ubuntu Mate 18.04 with Mate Desktop (Gnome 2 fork) and other applications give me a tray icon.
Only your application has this bug since version 2.0.

**Comment by atareao** [comment] 2018-06-03 13:12
@MartinX3 I use Ubuntu Mate 18.04 and It shows the icon. I don't understand why It doesn't show in yours. 
Besides I doesn't know how It is working without python3.
Please can you run `ps aux | grep python`?
Best regards

**Comment by MartinX3** [comment] 2018-06-03 14:54
Dear @atareao 

```bash
xxx@xxx xxx $ ps aux | grep python
root      1004  0.0  0.1 171132 15000 ?        Ssl  Jun02   0:00 /usr/bin/python3 /usr/bin/networkd-dispatcher
martin    2685  0.0  0.3 255228 28100 ?        Sl   Jun02   0:09 /usr/bin/python3 /usr/share/system-config-printer/applet.py
martin    2714  0.0  0.5 903996 43288 ?        Ssl  Jun02   0:05 /usr/bin/python3 /usr/bin/hp-systray -x
martin    2731  0.0  0.3 595372 28652 ?        Sl   Jun02   0:03 /usr/bin/python3 /usr/bin/gtk-redshift -t 6500:3700
martin    2757  0.0  0.5 693576 43568 ?        Sl   Jun02   0:02 /usr/bin/python3 /usr/bin/blueman-applet
martin    2852  0.0  0.2 260716 21944 ?        Sl   Jun02   0:14 /usr/bin/python3 /usr/bin/hp-systray -x
martin    2853  0.0  0.1 152880 14948 ?        S    Jun02   0:02 /usr/bin/python3 /usr/bin/hp-systray -x
martin    5281  0.0  0.0  14780  1108 pts/3    S+   16:53   0:00 grep --color=auto python
xxx@xxx xxx $ ps aux | grep touchpad
martin    5283  0.0  0.0  14780  1052 pts/3    S+   16:53   0:00 grep --color=auto touchpad
xxx@xxx xxx $ touchpad-indicator -s
<gettext.GNUTranslations object at 0x7f0f29c26ef0>
Another instance of Touchpad-Indicator is working
xxx@xxx xxx $ 
```

**Comment by atareao** [comment] 2018-06-03 19:40
Please do,
```
rm ~/.config/autostart/touchpad-indicator-autostart.desktop
rm -rf ~/.config/touchpad-indicator
```

Restart Ubuntu and run `touchpad-indicator` from terminal. Copy and paste here the output

Thanks

**Comment by MartinX3** [comment] 2018-06-03 19:56
Holy shit.

1. I removed the software
2. I removed the file and the folder.
3. I reinstalled the software
4. I runned the software from terminal
WIthout a restart.

It is working again and showing a tray icon.
So the upgrade to version 2.0 killed my config files.

Thank you very much.

**Closed** 2018-06-09 05:27 UTC

**Comment by shevchenkobn** [comment] 2019-02-17 20:25
The last solution worked for me, thank you.
My problem was caused when I ticked option "General options" => "Start Hidden" alongside with "Autostart enabled" and restarted my computer.
@atareao what is the expected behavior? Can the described behavior be considered as bug? Should I open an issue?

**Comment by tom-andersson** [comment] 2019-11-22 10:50
As @shevchenkobn said, this was caused by having 'Start hidden' and 'Autostart enabled' both selected for me. I fixed this with `vim ~/.config/touchpad-indicator/touchpad-indicator.conf` and changing `"start_hidden"` from `true` to `false`, restarted my desktop and the icon appeared in my tray again. No uninstall needed.
